version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: pos_postgres
    environment:
      POSTGRES_DB: pos_db
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pos_network

  # Redis for caching (optional but recommended for performance)
  redis:
    image: redis:7-alpine
    container_name: pos_redis
    ports:
      - "6379:6379"
    networks:
      - pos_network

  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pos_backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://pos_user:pos_password@postgres:5432/pos_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - pos_network
    command: npm run start:dev

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - pos_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  pos_network:
    driver: bridge
