// Mock API for demonstration (replace with your actual API)
export const salesHistoryApi = {
  sales: {
    getAll: async () => {
      // Simulate API delay
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Return demo data if API fails or no data
      return [
        {
          id: "cmb6cx7i6000cfcuwyok41ax8",
          saleNumber: "SAL-20250527-0004",
          totalAmount: 52281,
          tax: 4182.48,
          discount: 0,
          finalAmount: 56463.48,
          paymentMethod: "DIGITAL_WALLET",
          status: "COMPLETED",
          notes: "Necessitatibus cum a",
          customerName: "Armando Buckner",
          customerPhone: "+1 (389) 666-6007",
          amountReceived: null,
          changeAmount: null,
          createdAt: "2025-05-27T10:11:57.631Z",
          updatedAt: "2025-05-27T10:11:57.631Z",
          user: {
            id: "cmb5wdm430000fcn8g1oovpva",
            name: "Dylan Holman",
            email: "seno@mailinator.com",
            username: "vyzisyfeco",
            role: "CASHIER",
          },
          items: [
            {
              id: "cmb6cx7i6000efcuwsx259o4h",
              quantity: 72,
              unitPrice: 70,
              total: 5040,
              product: {
                id: "cmb5vpf950003fccgafp5ht1n",
                name: "Alika Ferguson",
                code: "RRR",
                price: 70,
              },
            },
            {
              id: "cmb6cx7i6000ffcuwx99iiyq9",
              quantity: 87,
              unitPrice: 543,
              total: 47241,
              product: {
                id: "cmb6ayzsz0000fcpgw6mteqcr",
                name: "Nehru Mccullough",
                code: "ZZZZ",
                price: 543,
              },
            },
          ],
        },
        {
          id: "cmb6cww730006fcuwqq4ak43r",
          saleNumber: "SAL-20250527-0003",
          totalAmount: 79104,
          tax: 6328.32,
          discount: 0,
          finalAmount: 85432.32,
          paymentMethod: "CARD",
          status: "COMPLETED",
          notes: "Architecto pariatur",
          customerName: "Ariana Wooten",
          customerPhone: "+1 (697) 951-8648",
          amountReceived: null,
          changeAmount: null,
          createdAt: "2025-05-27T10:11:42.975Z",
          updatedAt: "2025-05-27T10:11:42.975Z",
          user: {
            id: "cmb5wdm430000fcn8g1oovpva",
            name: "Dylan Holman",
            email: "seno@mailinator.com",
            username: "vyzisyfeco",
            role: "CASHIER",
          },
          items: [
            {
              id: "cmb6cww730008fcuwb1bwjbep",
              quantity: 57,
              unitPrice: 697,
              total: 39729,
              product: {
                id: "cmb5vp8ii0002fccgnopowvxs",
                name: "Neville Potts",
                code: "AAA",
                price: 697,
              },
            },
            {
              id: "cmb6cww730009fcuwwdy09rvx",
              quantity: 71,
              unitPrice: 111,
              total: 7881,
              product: {
                id: "cmb5vpl0x0004fccga3gy5jz7",
                name: "Ebony Benson",
                code: "XCXC",
                price: 111,
              },
            },
            {
              id: "cmb6cww73000afcuwwazdtjud",
              quantity: 58,
              unitPrice: 543,
              total: 31494,
              product: {
                id: "cmb6ayzsz0000fcpgw6mteqcr",
                name: "Nehru Mccullough",
                code: "ZZZZ",
                price: 543,
              },
            },
          ],
        },
        {
          id: "cmb6cwl000001fcuw5tsak8bn",
          saleNumber: "SAL-20250527-0002",
          totalAmount: 51405,
          tax: 4112.4,
          discount: 0,
          finalAmount: 55517.4,
          paymentMethod: "CASH",
          status: "COMPLETED",
          notes: "Facilis commodi ea e",
          customerName: "Jaden Norman",
          customerPhone: "+1 (335) 242-5251",
          amountReceived: 116666,
          changeAmount: 61148.6,
          createdAt: "2025-05-27T10:11:28.462Z",
          updatedAt: "2025-05-27T10:11:28.462Z",
          user: {
            id: "cmb5wdm430000fcn8g1oovpva",
            name: "Dylan Holman",
            email: "seno@mailinator.com",
            username: "vyzisyfeco",
            role: "CASHIER",
          },
          items: [
            {
              id: "cmb6cwl010003fcuw94dic2ld",
              quantity: 85,
              unitPrice: 543,
              total: 46155,
              product: {
                id: "cmb6ayzsz0000fcpgw6mteqcr",
                name: "Nehru Mccullough",
                code: "ZZZZ",
                price: 543,
              },
            },
            {
              id: "cmb6cwl010004fcuw4jr7s346",
              quantity: 75,
              unitPrice: 70,
              total: 5250,
              product: {
                id: "cmb5vpf950003fccgafp5ht1n",
                name: "Alika Ferguson",
                code: "RRR",
                price: 70,
              },
            },
          ],
        },
        {
          id: "cmb6cb9pa0001fc9o5xmeicko",
          saleNumber: "SAL-20250527-0001",
          totalAmount: 17985,
          tax: 1438.8,
          discount: 0,
          finalAmount: 19423.8,
          paymentMethod: "CASH",
          status: "COMPLETED",
          notes: "Est voluptas vel est",
          customerName: "Carlos Wilson",
          customerPhone: "+1 (627) 113-7928",
          amountReceived: 90000,
          changeAmount: 70576.2,
          createdAt: "2025-05-27T09:54:54.043Z",
          updatedAt: "2025-05-27T09:54:54.043Z",
          user: {
            id: "cmb5wdm430000fcn8g1oovpva",
            name: "Dylan Holman",
            email: "seno@mailinator.com",
            username: "vyzisyfeco",
            role: "CASHIER",
          },
          items: [
            {
              id: "cmb6cb9pb0003fc9ovzn1nn50",
              quantity: 25,
              unitPrice: 697,
              total: 17425,
              product: {
                id: "cmb5vp8ii0002fccgnopowvxs",
                name: "Neville Potts",
                code: "AAA",
                price: 697,
              },
            },
            {
              id: "cmb6cb9pb0004fc9ogd5vgx16",
              quantity: 8,
              unitPrice: 70,
              total: 560,
              product: {
                id: "cmb5vpf950003fccgafp5ht1n",
                name: "Alika Ferguson",
                code: "RRR",
                price: 70,
              },
            },
          ],
        },
      ];
    },
  },
};
