// Mock API for demonstration (replace with your actual API)
export const salesHistoryApi = {
  sales: {
    getAll: async () => {
      // Simulate API delay
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Return demo data if API fails or no data
      return [
        {
          id: "TXN-001",
          createdAt: "2025-05-26T10:30:00Z",
          totalAmount: 125.5,
          paymentMethod: "card",
          customerName: "John Doe",
          customerPhone: "+1234567890",
          items: [
            {
              productId: "1",
              productName: "Premium Coffee Beans",
              productCode: "PCB-001",
              quantity: 2,
              price: 25.0,
            },
            {
              productId: "2",
              productName: "Ceramic Mug Set",
              productCode: "CMS-002",
              quantity: 3,
              price: 25.17,
            },
          ],
          subtotal: 125.5,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-002",
          createdAt: "2025-05-26T09:15:00Z",
          totalAmount: 89.99,
          paymentMethod: "cash",
          customerName: "Sarah Wilson",
          customerPhone: "+987654321",
          items: [
            {
              productId: "3",
              productName: "Artisan Chocolate Box",
              productCode: "ACB-003",
              quantity: 1,
              price: 45.0,
            },
            {
              productId: "4",
              productName: "Organic Tea Collection",
              productCode: "OTC-004",
              quantity: 1,
              price: 44.99,
            },
          ],
          subtotal: 89.99,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-003",
          createdAt: "2025-05-25T16:45:00Z",
          totalAmount: 67.25,
          paymentMethod: "digital",
          customerName: "Mike Johnson",
          customerPhone: "+112233445566",
          items: [
            {
              productId: "5",
              productName: "Wireless Earbuds",
              productCode: "WE-005",
              quantity: 1,
              price: 67.25,
            },
          ],
          subtotal: 67.25,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-004",
          createdAt: "2025-05-25T14:22:00Z",
          totalAmount: 234.8,
          paymentMethod: "card",
          customerName: "Emily Davis",
          customerPhone: "+99887766544",
          items: [
            {
              productId: "6",
              productName: "Smart Watch Pro",
              productCode: "SWP-006",
              quantity: 1,
              price: 199.99,
            },
            {
              productId: "7",
              productName: "Phone Case Premium",
              productCode: "PCP-007",
              quantity: 2,
              price: 17.4,
            },
          ],
          subtotal: 234.8,
          taxAmount: 0,
          status: "refunded",
        },
        {
          id: "TXN-005",
          createdAt: "2025-05-24T11:30:00Z",
          totalAmount: 156.75,
          paymentMethod: "cash",
          customerName: "David Brown",
          customerPhone: "+8855336644",
          items: [
            {
              productId: "8",
              productName: "Bluetooth Speaker",
              productCode: "BS-008",
              quantity: 1,
              price: 89.99,
            },
            {
              productId: "9",
              productName: "USB-C Cable Pack",
              productCode: "UCP-009",
              quantity: 3,
              price: 22.25,
            },
          ],
          subtotal: 156.75,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-006",
          createdAt: "2025-05-24T09:45:00Z",
          totalAmount: 445.3,
          paymentMethod: "card",
          customerName: "Lisa Anderson",
          customerPhone: "+5566778899",
          items: [
            {
              productId: "10",
              productName: "Gaming Laptop Stand",
              productCode: "GLS-010",
              quantity: 1,
              price: 129.99,
            },
            {
              productId: "11",
              productName: "Mechanical Keyboard RGB",
              productCode: "MKR-011",
              quantity: 1,
              price: 185.5,
            },
            {
              productId: "12",
              productName: "Wireless Gaming Mouse",
              productCode: "WGM-012",
              quantity: 1,
              price: 89.99,
            },
            {
              productId: "13",
              productName: "Monitor Screen Cleaner",
              productCode: "MSC-013",
              quantity: 2,
              price: 19.91,
            },
          ],
          subtotal: 445.3,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-007",
          createdAt: "2025-05-23T15:20:00Z",
          totalAmount: 78.45,
          paymentMethod: "digital",
          customerName: "Robert Chen",
          customerPhone: "+2233445566",
          items: [
            {
              productId: "14",
              productName: "Fitness Tracker Band",
              productCode: "FTB-014",
              quantity: 1,
              price: 59.99,
            },
            {
              productId: "15",
              productName: "Water Bottle Smart",
              productCode: "WBS-015",
              quantity: 1,
              price: 18.46,
            },
          ],
          subtotal: 78.45,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-008",
          createdAt: "2025-05-23T12:30:00Z",
          totalAmount: 312.75,
          paymentMethod: "cash",
          customerName: "Jennifer Martinez",
          customerPhone: "+7788990011",
          items: [
            {
              productId: "16",
              productName: "Air Purifier Compact",
              productCode: "APC-016",
              quantity: 1,
              price: 199.99,
            },
            {
              productId: "17",
              productName: "Essential Oil Diffuser",
              productCode: "EOD-017",
              quantity: 1,
              price: 79.99,
            },
            {
              productId: "18",
              productName: "Aromatherapy Oil Set",
              productCode: "AOS-018",
              quantity: 1,
              price: 32.77,
            },
          ],
          subtotal: 312.75,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-009",
          createdAt: "2025-05-22T17:10:00Z",
          totalAmount: 189.97,
          paymentMethod: "card",
          customerName: "Kevin Thompson",
          customerPhone: "+3344556677",
          items: [
            {
              productId: "19",
              productName: "Smart Home Hub",
              productCode: "SHH-019",
              quantity: 1,
              price: 149.99,
            },
            {
              productId: "20",
              productName: "LED Smart Bulbs 4-Pack",
              productCode: "LSB-020",
              quantity: 1,
              price: 39.98,
            },
          ],
          subtotal: 189.97,
          taxAmount: 0,
          status: "pending",
        },
        {
          id: "TXN-010",
          createdAt: "2025-05-22T14:45:00Z",
          totalAmount: 267.85,
          paymentMethod: "digital",
          customerName: "Amanda Rodriguez",
          customerPhone: "+9900112233",
          items: [
            {
              productId: "21",
              productName: "Yoga Mat Premium",
              productCode: "YMP-021",
              quantity: 1,
              price: 45.99,
            },
            {
              productId: "22",
              productName: "Resistance Bands Set",
              productCode: "RBS-022",
              quantity: 1,
              price: 29.99,
            },
            {
              productId: "23",
              productName: "Foam Roller Professional",
              productCode: "FRP-023",
              quantity: 1,
              price: 89.99,
            },
            {
              productId: "24",
              productName: "Protein Powder Vanilla",
              productCode: "PPV-024",
              quantity: 1,
              price: 101.88,
            },
          ],
          subtotal: 267.85,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-011",
          createdAt: "2025-05-21T16:30:00Z",
          totalAmount: 523.4,
          paymentMethod: "card",
          customerName: "Thomas Wilson",
          customerPhone: "+1122334455",
          items: [
            {
              productId: "25",
              productName: "Professional Camera Lens",
              productCode: "PCL-025",
              quantity: 1,
              price: 399.99,
            },
            {
              productId: "26",
              productName: "Camera Tripod Carbon",
              productCode: "CTC-026",
              quantity: 1,
              price: 89.99,
            },
            {
              productId: "27",
              productName: "Memory Card 128GB",
              productCode: "MC-027",
              quantity: 2,
              price: 33.42,
            },
          ],
          subtotal: 523.4,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-012",
          createdAt: "2025-05-21T11:15:00Z",
          totalAmount: 145.67,
          paymentMethod: "cash",
          customerName: "Maria Garcia",
          customerPhone: "+6677889900",
          items: [
            {
              productId: "28",
              productName: "Kitchen Scale Digital",
              productCode: "KSD-028",
              quantity: 1,
              price: 39.99,
            },
            {
              productId: "29",
              productName: "Spice Rack Bamboo",
              productCode: "SRB-029",
              quantity: 1,
              price: 79.99,
            },
            {
              productId: "30",
              productName: "Cooking Utensil Set",
              productCode: "CUS-030",
              quantity: 1,
              price: 25.69,
            },
          ],
          subtotal: 145.67,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-013",
          createdAt: "2025-05-20T13:20:00Z",
          totalAmount: 89.95,
          paymentMethod: "digital",
          customerName: "Christopher Lee",
          customerPhone: "+4455667788",
          items: [
            {
              productId: "31",
              productName: "Book Light LED",
              productCode: "BLL-031",
              quantity: 2,
              price: 19.99,
            },
            {
              productId: "32",
              productName: "Bookmark Set Leather",
              productCode: "BSL-032",
              quantity: 1,
              price: 24.99,
            },
            {
              productId: "33",
              productName: "Journal Hardcover",
              productCode: "JH-033",
              quantity: 1,
              price: 24.98,
            },
          ],
          subtotal: 89.95,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-014",
          createdAt: "2025-05-20T10:05:00Z",
          totalAmount: 378.25,
          paymentMethod: "card",
          customerName: "Nicole White",
          customerPhone: "+8899001122",
          items: [
            {
              productId: "34",
              productName: "Electric Scooter Foldable",
              productCode: "ESF-034",
              quantity: 1,
              price: 299.99,
            },
            {
              productId: "35",
              productName: "Helmet Safety Pro",
              productCode: "HSP-035",
              quantity: 1,
              price: 49.99,
            },
            {
              productId: "36",
              productName: "LED Light Strip 5m",
              productCode: "LLS-036",
              quantity: 1,
              price: 28.27,
            },
          ],
          subtotal: 378.25,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-015",
          createdAt: "2025-05-19T15:40:00Z",
          totalAmount: 167.89,
          paymentMethod: "cash",
          customerName: "Daniel Kim",
          customerPhone: "+5566778800",
          items: [
            {
              productId: "37",
              productName: "Backpack Travel Pro",
              productCode: "BTP-037",
              quantity: 1,
              price: 119.99,
            },
            {
              productId: "38",
              productName: "Travel Organizer Set",
              productCode: "TOS-038",
              quantity: 1,
              price: 29.99,
            },
            {
              productId: "39",
              productName: "Luggage Tags Premium",
              productCode: "LTP-039",
              quantity: 3,
              price: 17.91,
            },
          ],
          subtotal: 167.89,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-016",
          createdAt: "2025-05-19T08:25:00Z",
          totalAmount: 234.5,
          paymentMethod: "digital",
          customerName: "Rachel Taylor",
          customerPhone: "+7788990055",
          items: [
            {
              productId: "40",
              productName: "Standing Desk Converter",
              productCode: "SDC-040",
              quantity: 1,
              price: 189.99,
            },
            {
              productId: "41",
              productName: "Ergonomic Mouse Pad",
              productCode: "EMP-041",
              quantity: 1,
              price: 24.99,
            },
            {
              productId: "42",
              productName: "Blue Light Glasses",
              productCode: "BLG-042",
              quantity: 1,
              price: 19.52,
            },
          ],
          subtotal: 234.5,
          taxAmount: 0,
          status: "refunded",
        },
        {
          id: "TXN-017",
          createdAt: "2025-05-18T19:30:00Z",
          totalAmount: 456.78,
          paymentMethod: "card",
          customerName: "Steven Adams",
          customerPhone: "+2233445500",
          items: [
            {
              productId: "43",
              productName: "Coffee Machine Espresso",
              productCode: "CME-043",
              quantity: 1,
              price: 349.99,
            },
            {
              productId: "44",
              productName: "Coffee Grinder Burr",
              productCode: "CGB-044",
              quantity: 1,
              price: 79.99,
            },
            {
              productId: "45",
              productName: "Espresso Cups Set",
              productCode: "ECS-045",
              quantity: 1,
              price: 26.8,
            },
          ],
          subtotal: 456.78,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-018",
          createdAt: "2025-05-18T14:15:00Z",
          totalAmount: 98.76,
          paymentMethod: "cash",
          customerName: "Michelle Clark",
          customerPhone: "+9900112200",
          items: [
            {
              productId: "46",
              productName: "Plant Pot Ceramic Large",
              productCode: "PPCL-046",
              quantity: 2,
              price: 24.99,
            },
            {
              productId: "47",
              productName: "Succulent Plant Mix",
              productCode: "SPM-047",
              quantity: 4,
              price: 12.195,
            },
          ],
          subtotal: 98.76,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-019",
          createdAt: "2025-05-17T16:50:00Z",
          totalAmount: 299.99,
          paymentMethod: "digital",
          customerName: "Jason Turner",
          customerPhone: "+1133557799",
          items: [
            {
              productId: "48",
              productName: "Tablet 10-inch Android",
              productCode: "TTA-048",
              quantity: 1,
              price: 249.99,
            },
            {
              productId: "49",
              productName: "Tablet Case Keyboard",
              productCode: "TCK-049",
              quantity: 1,
              price: 50.0,
            },
          ],
          subtotal: 299.99,
          taxAmount: 0,
          status: "completed",
        },
        {
          id: "TXN-020",
          createdAt: "2025-05-17T12:10:00Z",
          totalAmount: 567.84,
          paymentMethod: "card",
          customerName: "Lauren Phillips",
          customerPhone: "+4466778811",
          items: [
            {
              productId: "50",
              productName: "Robot Vacuum Premium",
              productCode: "RVP-050",
              quantity: 1,
              price: 399.99,
            },
            {
              productId: "51",
              productName: "Vacuum Replacement Filters",
              productCode: "VRF-051",
              quantity: 2,
              price: 29.99,
            },
            {
              productId: "52",
              productName: "Smart Home App Subscription",
              productCode: "SHAS-052",
              quantity: 12,
              price: 107.86,
            },
          ],
          subtotal: 567.84,
          taxAmount: 0,
          status: "completed",
        },
      ];
    },
  },
};
